### ISSUE TITLE
[Feature Request] option to delete the invocation message

### ISSUE THREAD

**Issue by snwflake** [padtrack/track#2]
Currently the invocation of the `render` command leaves a trail of 3 total messages.

The invocation message including the replay, the process indicator and the final render. I would love to see an option to have either or both preceding messages to be deleted upon task completion.

**Comment by padtrack** [comment]
The invocation's attachment is hidden in slash commands, which will be released soon. As for the latter two, I'll look into merging them.

**Comment by padtrack** [comment]
This is implemented in the rewrite. I found no good alternative to sending a status message and follow-up message as the follow-up message now has buttons.
