### ISSUE TITLE
cfg.redis.host not working on bot/extensions/render.py

### ISSUE THREAD

**Issue by YukariMazeDofu** [padtrack/track#3]
I set a non-local host on redis_host in secrets.ini, but it runs not correctry.
Is this line wrong?

On `bot/extensions/render.py`
https://github.com/padtrack/track/blob/efe4555ee8047c846c9f787f48606cd4fc4810fd/bot/extensions/render.py#L24

On `bot/worker.py`
https://github.com/padtrack/track/blob/efe4555ee8047c846c9f787f48606cd4fc4810fd/bot/worker.py#L18

**Comment by padtrack** [comment]
Is your Redis server not running on the same machine as the bot?

**Comment by YukariMazeDofu** [comment]
> Is your Redis server not running on the same machine as the bot?

No, I prepared my redis server using docker-compose.
This server's hostname is `redis`. not `localhost`.
I changed `_url` value in render.py to same as in worker.py, It works correctry.

**Comment by padtrack** [comment]
Okay.
