### ISSUE TITLE
Small bugs/Edge cases for "outspot" feature

### ISSUE THREAD

**Issue by rhulkb27** [padtrack/track#4]
1. Commonwealth destroyers can just be "Haida"
2. Black Friday ships should be deleted
3. Legendary gearing
4. Secondary build ships like Massachusetts, Georgia, and Agir (coming soon™)
5. Z-39 slot-5-at-t7-bs
6. Pan American ships.

Feel free to add onto this list with more edge cases with regards to concealment.

**Comment by Max-55555** [comment]
Why do I care if a cv outspots me? That can be removed.
